### ISSUE TITLE
Docker container started but UI not reachable 

### ISSUE THREAD

**Issue by geppo1988** [grimsi/accservermanager#24]
Hi,

thanks for the great job!

I'm currently not able to access the UI after I started th container.

Am I missing something? is there any log I could check to troubleshoot the problem?

Regards

**Comment by geppo1988** [comment]
It looks like after 3 minutes of waiting that the server works :) Sorry

**Comment by grimsi** [comment]
With "docker logs <container-name>" you should be able to see the logs of the accservermanager. Are you sure that the relevant ports are forwarded in your firewall?

**Comment by geppo1988** [comment]
I managed to solve the problem....now I just realized that ACC 1.0 is not yet supported...am I right?

**Comment by grimsi** [comment]
Sadly yes. Kunos changed a lot of stuff when they released version 1.0 and more recent versions. Since I quit playing ACC and I started new projects with friends I did not finish implementing the changes. You may want to check out https://github.com/gotzl/accservermanager , I think this one has Support for recent ACC versions.
Maybe I will update this one in the future but I don't want to make any promises.
