### ISSUE TITLE
Editing config files - When server patches come out to add new features

### ISSUE THREAD

**Issue by GazCBG** [grimsi/accservermanager#5]
When the server filess get an update, it maybe a good idea to add a textbox at the bottom of both event and server configs, to add any extra that is required.

I am thinking in the event if you are not able to update the system as soon as a server patch comes out.

Or maybe add an advanced section where change the config files manually via the panel.

**Comment by grimsi** [comment]
Thanks for your feedback :)
I get the idea and I think that this feature could indeed be useful.
However for me it has a very low priority because of two reasons:
1. I think it's pretty complex to implement because you would have different versions of configs and my backend can't manage that at the moment
2. As soon as version 1.0 releases (which will hopefully be soon) the config should be final and never or at least very rarely change. So this feature would just be useful in the early-access phase (which wont last much longer, at least I hope so).

I will still take a closer look at it and think about how to implement this because user-editable configurations can be useful

**Comment by grimsi** [comment]
I just noticed your second suggestion.
It is already possible to manually edit the config files.
You have to add the new accServer.exe to the backend, then update the server version using the website, then restart the server and then you can edit the config as you want and restart again.
I know this process is a bit complicated but at least it should be good enough to bridge the time until I release an update for my server manager
